name: Create GitHub Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # Se dispara con tags como v1.0.0, v1.2.3, etc.

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # Necesario para crear el release y subir artefactos

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Paso principal: Crear el Release en GitHub
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }} # Toma el nombre del tag que disparó el workflow
          release_name: Release ${{ github.ref_name }}
          body: |
            ## 🎉 Nuevo Release! 🎉
            
          draft: false
          prerelease: false