name: SonarCloud PR Scan

on:
  workflow_run:
    workflows: ["Frontend CI"]
    types:
      - completed

jobs:
  sonarcloud-analysis:
    name: SonarCloud Analysis for PRs
    runs-on: ubuntu-latest
    # Solo ejecuta este job si el workflow "Frontend CI" fue por un PR y fue exitoso
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          # Checkout el código del HEAD del PR que disparó el workflow_run
          repository: ${{ github.event.workflow_run.pull_requests[0].head.repo.full_name }}
          ref: ${{ github.event.workflow_run.head_sha }}
          fetch-depth: 0 # SonarCloud necesita el historial completo

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'

      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          # El artifact fue creado por el workflow run que disparó este
          run-id: ${{ github.event.workflow_run.id }}
          path: coverage # Descarga al directorio 'coverage'

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Este GITHUB_TOKEN tiene permisos de escritura
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Este es el secret de tu repo principal